Repository Vladacdc/TransIT.Client, pull requests merged in 2019-08, with the labels that each got.

#15 Add more columns to users table view.
  src/app/modules/admin/component/users/users.component.ts
Labels: bug

#22 Rename property same way as back-end
  src/app/modules/admin/component/issue-log/issue-log.component.ts
  src/app/modules/engineer/components/issue-log-components/issue-logs/issue-logs.component.ts
  src/app/modules/shared/components/global-issue/global-issue.component.ts
  src/app/modules/shared/components/issue-log/issue-log.component.ts
  src/app/modules/shared/models/issue.ts
  src/app/modules/shared/models/issuelog.ts
  src/app/modules/shared/models/post.ts
  src/app/modules/shared/models/supplier.ts
Labels: bug

#23 Use angular date picker component and fix bugs in filtering by date
  src/app/modules/shared/components/filters-tabs/filters-tabs.component.html
  src/app/modules/shared/components/filters-tabs/filters-tabs.component.scss
  src/app/modules/shared/components/filters-tabs/filters-tabs.component.ts
  src/app/modules/shared/shared.module.ts
Labels: bug

#25 Fix 2 bugs
  src/app/modules/admin/component/users/edit-user/edit-user.component.ts
  src/app/modules/admin/component/vehicles/vehicles.component.ts
  src/app/modules/register/components/issues/issues.component.ts
Labels: bug

#30 Reworked supplier edit and create
  src/app/modules/shared/components/supplier/create-supplier/create-supplier.component.html
  src/app/modules/shared/components/supplier/create-supplier/create-supplier.component.ts
  src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.html
  src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.ts
Labels: bug

#29 Inputs weren't red after failed login
  src/app/modules/core/components/login/login.component.ts
Labels: bug

#32 Report Tab 1.1
  src/app/modules/analyst/components/report/report.component.html
  src/app/modules/analyst/components/report/report.component.ts
  src/app/modules/shared/services/malfunction-subgroup.service.ts
  src/app/modules/shared/services/malfunction.service.ts
  src/app/modules/shared/services/statistics.service.ts
  src/app/modules/shared/shared.module.ts
Labels: enhancement

#33 Added breadcrumb and back button
  src/app/modules/admin/component/admin/admin.component.html
  src/app/modules/admin/component/admin/admin.component.scss
  src/app/modules/analyst/components/analyst/analyst.component.html
  src/app/modules/engineer/components/engineer/engineer.component.html
  src/app/modules/shared/components/breadcrumb/breadcrumb.component.html
  src/app/modules/shared/components/breadcrumb/breadcrumb.component.scss
  src/app/modules/shared/components/breadcrumb/breadcrumb.component.spec.ts
  src/app/modules/shared/components/breadcrumb/breadcrumb.component.ts
  src/app/modules/shared/shared.module.ts
Labels: enhancement

#34 Employee-user attachment functionality
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/component/edit-malfunc/edit-malfunc.component.ts
  src/app/modules/admin/component/employees/attach-user/attach-user.component.html
  src/app/modules/admin/component/employees/attach-user/attach-user.component.scss
  src/app/modules/admin/component/employees/attach-user/attach-user.component.ts
  src/app/modules/admin/component/employees/employees.component.html
  src/app/modules/admin/component/employees/employees.component.ts
  src/app/modules/admin/component/users/create-user/create-user.component.html
  src/app/modules/admin/component/users/create-user/create-user.component.ts
  src/app/modules/admin/component/users/edit-user/edit-user.component.html
  src/app/modules/admin/component/users/edit-user/edit-user.component.ts
  src/app/modules/admin/component/users/users.component.ts
  src/app/modules/shared/models/employee.ts
  src/app/modules/shared/models/user.ts
  src/app/modules/shared/services/employee.service.ts
Labels: feature

#38 Add basic generic table
  src/app/modules/analyst/analyst.module.ts
  src/app/modules/core/models/data-table-request.ts
  src/app/modules/core/services/crud.service.ts
  src/app/modules/shared/components/supplier/create-supplier/create-supplier.component.ts
  src/app/modules/shared/components/supplier/delete-supplier/delete-supplier.component.html
  src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.html
  src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.ts
  src/app/modules/shared/components/supplier/supplier.component.html
  src/app/modules/shared/components/supplier/supplier.component.scss
  src/app/modules/shared/components/supplier/supplier.component.ts
  src/app/modules/shared/components/tables/mat-fsp-table/mat-fsp-table.component.html
  src/app/modules/shared/components/tables/mat-fsp-table/mat-fsp-table.component.scss
  src/app/modules/shared/components/tables/mat-fsp-table/mat-fsp-table.component.spec.ts
  src/app/modules/shared/components/tables/mat-fsp-table/mat-fsp-table.component.ts
  src/app/modules/shared/data-sources/entities-data-sourse.ts
  src/app/modules/shared/models/supplier.ts
  src/app/modules/shared/paginator-extentions/mat-paginator-intl-custom.ts
  src/app/modules/shared/services/supplier.service.ts
  src/app/modules/shared/shared.module.ts
Labels: enhancement, feature

#42 Added Localization
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/modules/admin/component/admin/admin-navbar/admin-navbar.component.html
  src/app/modules/core/components/login/login.component.html
  src/app/modules/core/components/login/login.component.scss
  src/app/modules/core/components/login/login.component.ts
  src/app/modules/core/components/navbar/navbar.component.html
  src/app/modules/core/components/validator/validator.component.html
  src/app/modules/core/components/validator/validator.component.scss
  src/app/modules/core/components/validator/validator.component.ts
  src/app/modules/core/core.module.ts
  src/app/modules/core/interceptors/http-error.interceptor.ts
  src/app/modules/core/services/authentication.service.ts
  src/app/modules/localization/language-select/language-select.component.html
  src/app/modules/localization/language-select/language-select.component.scss
  src/app/modules/localization/language-select/language-select.component.ts
  src/app/modules/localization/localization.module.ts
  src/assets/translate/core/en.json
  src/assets/translate/core/uk.json
  src/assets/translate/en.json
  src/assets/translate/uk.json
Labels: feature

#44 Improved Breadcrumb and more
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/component/admin/admin-navbar/admin-navbar.component.html
  src/app/modules/admin/component/admin/admin-navbar/admin-navbar.component.scss
  src/app/modules/admin/component/admin/admin-navbar/admin-navbar.component.spec.ts
  src/app/modules/admin/component/admin/admin-navbar/admin-navbar.component.ts
  src/app/modules/admin/component/admin/admin.component.html
  src/app/modules/admin/component/employees/employees.component.html
  src/app/modules/admin/component/posts/posts.component.html
  src/app/modules/analyst/analyst-routing.module.ts
  src/app/modules/analyst/components/analyst/analyst.component.html
  src/app/modules/analyst/components/analyst/analyst.component.scss
  src/app/modules/engineer/components/engineer/engineer.component.scss
  src/app/modules/localization/localization.module.ts
  src/app/modules/shared/components/breadcrumb/breadcrumb.component.ts
  src/assets/translate/routing/en.json
  src/assets/translate/routing/uk.json
Labels: enhancement
